---
name: ci

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  call-rsync-deploy:
    name: Call Rsync Deploy

    uses: geocoug/github-actions-templates/.github/workflows/rsync-deploy.yml@main

    permissions:
      contents: read

    secrets:
      host: ${{ secrets.HOST }}
      username: ${{ secrets.USERNAME }}
      target-directory: ${{ secrets.TARGET_DIRECTORY }}
      ssh-key: ${{ secrets.SSH_KEY }}
    with:
      rsync-delete: true
